# Exploratory Data Analysis MIMIC III

In [6]:
import sqlite3
import pandas as pd

pd.set_option('display.max_colwidth', None)  # Show full content of columns
pd.set_option('display.max_rows', None)      # Show all rows

# Determine DB schema

In [2]:
# Connect to sql db 
conn = sqlite3.connect("../db/mimic.db")

# Determine what tables Exist 
pd.read_sql(
    """
    SELECT name 
    FROM sqlite_master
    WHERE type='table' 
    ORDER BY name
    """,
    conn
)

                  name
0           admissions
1              callout
2           caregivers
3          chartevents
4            cptevents
5      d_icd_diagnoses
6     d_icd_procedures
7              d_items
8           d_labitems
9       datetimeevents
10       diagnoses_icd
11            drgcodes
12            icustays
13      inputevents_cv
14      inputevents_mv
15           labevents
16  microbiologyevents
17        outputevents
18            patients
19       prescriptions
20      procedures_icd
21            services
22           transfers

In [ ]:
# As it can be tedious to write all the names this is a query generator. Now we just copy paste into the actual query we want
print(pd.read_sql(
    """
    SELECT 'SELECT ''' || name || ''' AS table_name, COUNT(*) AS row_count FROM ' || name || ' UNION ALL'
    FROM sqlite_master 
    WHERE type='table'; 
    """, 
    conn
))

        'SELECT ''' || name || ''' AS table_name, COUNT(*) AS row_count FROM ' || name || ' UNION ALL'
0                       SELECT 'patients' AS table_name, COUNT(*) AS row_count FROM patients UNION ALL
1                   SELECT 'admissions' AS table_name, COUNT(*) AS row_count FROM admissions UNION ALL
2                       SELECT 'icustays' AS table_name, COUNT(*) AS row_count FROM icustays UNION ALL
3                 SELECT 'chartevents' AS table_name, COUNT(*) AS row_count FROM chartevents UNION ALL
4                     SELECT 'labevents' AS table_name, COUNT(*) AS row_count FROM labevents UNION ALL
5               SELECT 'outputevents' AS table_name, COUNT(*) AS row_count FROM outputevents UNION ALL
6           SELECT 'inputevents_cv' AS table_name, COUNT(*) AS row_count FROM inputevents_cv UNION ALL
7           SELECT 'inputevents_mv' AS table_name, COUNT(*) AS row_count FROM inputevents_mv UNION ALL
8             SELECT 'prescriptions' AS table_name, COUNT(*) AS row_count FROM prescriptions UNION ALL
9           SELECT 'procedures_icd' AS table_name, COUNT(*) AS row_count FROM procedures_icd UNION ALL
10            SELECT 'diagnoses_icd' AS table_name, COUNT(*) AS row_count FROM diagnoses_icd UNION ALL
11        SELECT 'd_icd_diagnoses' AS table_name, COUNT(*) AS row_count FROM d_icd_diagnoses UNION ALL
12      SELECT 'd_icd_procedures' AS table_name, COUNT(*) AS row_count FROM d_icd_procedures UNION ALL
13                        SELECT 'd_items' AS table_name, COUNT(*) AS row_count FROM d_items UNION ALL
14                  SELECT 'd_labitems' AS table_name, COUNT(*) AS row_count FROM d_labitems UNION ALL
15  SELECT 'microbiologyevents' AS table_name, COUNT(*) AS row_count FROM microbiologyevents UNION ALL
16          SELECT 'datetimeevents' AS table_name, COUNT(*) AS row_count FROM datetimeevents UNION ALL
17                        SELECT 'callout' AS table_name, COUNT(*) AS row_count FROM callout UNION ALL
18                  SELECT 'caregivers' AS table_name, COUNT(*) AS row_count FROM caregivers UNION ALL
19                      SELECT 'services' AS table_name, COUNT(*) AS row_count FROM services UNION ALL
20                    SELECT 'transfers' AS table_name, COUNT(*) AS row_count FROM transfers UNION ALL
21                    SELECT 'cptevents' AS table_name, COUNT(*) AS row_count FROM cptevents UNION ALL
22                      SELECT 'drgcodes' AS table_name, COUNT(*) AS row_count FROM drgcodes UNION ALL

In [ ]:
# View row counts of each Table (Should only be 100 Patients as its the DEMO Version of MIMIC 3)
pd.read_sql(
    """
    SELECT 'patients' AS table_name, COUNT(*) AS row_count FROM patients UNION ALL
    SELECT 'admissions' AS table_name, COUNT(*) AS row_count FROM admissions UNION ALL
    SELECT 'icustays' AS table_name, COUNT(*) AS row_count FROM icustays UNION ALL
    SELECT 'chartevents' AS table_name, COUNT(*) AS row_count FROM chartevents UNION ALL
    SELECT 'labevents' AS table_name, COUNT(*) AS row_count FROM labevents UNION ALL
    SELECT 'outputevents' AS table_name, COUNT(*) AS row_count FROM outputevents UNION ALL
    SELECT 'inputevents_cv' AS table_name, COUNT(*) AS row_count FROM inputevents_cv UNION ALL
    SELECT 'inputevents_mv' AS table_name, COUNT(*) AS row_count FROM inputevents_mv UNION ALL
    SELECT 'prescriptions' AS table_name, COUNT(*) AS row_count FROM prescriptions UNION ALL
    SELECT 'procedures_icd' AS table_name, COUNT(*) AS row_count FROM procedures_icd UNION ALL
    SELECT 'diagnoses_icd' AS table_name, COUNT(*) AS row_count FROM diagnoses_icd UNION ALL
    SELECT 'd_icd_diagnoses' AS table_name, COUNT(*) AS row_count FROM d_icd_diagnoses UNION ALL
    SELECT 'd_icd_procedures' AS table_name, COUNT(*) AS row_count FROM d_icd_procedures UNION ALL
    SELECT 'd_items' AS table_name, COUNT(*) AS row_count FROM d_items UNION ALL
    SELECT 'd_labitems' AS table_name, COUNT(*) AS row_count FROM d_labitems UNION ALL
    SELECT 'microbiologyevents' AS table_name, COUNT(*) AS row_count FROM microbiologyevents UNION ALL
    SELECT 'datetimeevents' AS table_name, COUNT(*) AS row_count FROM datetimeevents UNION ALL
    SELECT 'callout' AS table_name, COUNT(*) AS row_count FROM callout UNION ALL
    SELECT 'caregivers' AS table_name, COUNT(*) AS row_count FROM caregivers UNION ALL
    SELECT 'services' AS table_name, COUNT(*) AS row_count FROM services UNION ALL
    SELECT 'transfers' AS table_name, COUNT(*) AS row_count FROM transfers UNION ALL
    SELECT 'cptevents' AS table_name, COUNT(*) AS row_count FROM cptevents UNION ALL
    SELECT 'drgcodes' AS table_name, COUNT(*) AS row_count FROM drgcodes
    """,
    conn
)

            table_name  row_count
0             patients        100
1           admissions        129
2             icustays        136
3          chartevents     758355
4            labevents      76074
5         outputevents      11320
6       inputevents_cv      34799
7       inputevents_mv      13224
8        prescriptions      10398
9       procedures_icd        506
10       diagnoses_icd       1761
11     d_icd_diagnoses      14567
12    d_icd_procedures       3882
13             d_items      12487
14          d_labitems        753
15  microbiologyevents       2003
16      datetimeevents      15551
17             callout         77
18          caregivers       7567
19            services        163
20           transfers        524
21           cptevents       1579
22            drgcodes        297

In [11]:
# View each table for 5 rows 
tables = conn.execute(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
).fetchall()

for (t,) in tables:
    print(f"\n{'='*60}")
    print(f" {t.upper()}")
    print(f"{'='*60}")
    display(pd.read_sql(f"SELECT * FROM {t} LIMIT 5", conn))

============================================================
 ADMISSIONS
============================================================

,row_id,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,edregtime,edouttime,diagnosis,hospital_expire_flag,has_chartevents_data
0,12258,10006,142345,2164-10-23 21:09:00,2164-11-01 17:15:00,None,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,None,CATHOLIC,SEPARATED,BLACK/AFRICAN AMERICAN,2164-10-23 16:43:00,2164-10-23 23:00:00,SEPSIS,0,1
1,12263,10011,105331,2126-08-14 22:32:00,2126-08-28 18:59:00,2126-08-28 18:59:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,Private,None,CATHOLIC,SINGLE,UNKNOWN/NOT SPECIFIED,None,None,HEPATITIS B,1,1
2,12265,10013,165520,2125-10-04 23:36:00,2125-10-07 15:13:00,2125-10-07 15:13:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,Medicare,None,CATHOLIC,None,UNKNOWN/NOT SPECIFIED,None,None,SEPSIS,1,1
3,12269,10017,199207,2149-05-26 17:19:00,2149-06-03 18:42:00,None,EMERGENCY,EMERGENCY ROOM ADMIT,SNF,Medicare,None,CATHOLIC,DIVORCED,WHITE,2149-05-26 12:08:00,2149-05-26 19:45:00,HUMERAL FRACTURE,0,1
4,12270,10019,177759,2163-05-14 20:43:00,2163-05-15 12:00:00,2163-05-15 12:00:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,DEAD/EXPIRED,Medicare,None,CATHOLIC,DIVORCED,WHITE,None,None,ALCOHOLIC HEPATITIS,1,1

============================================================
 CALLOUT
============================================================

,row_id,subject_id,hadm_id,submit_wardid,submit_careunit,curr_wardid,curr_careunit,callout_wardid,callout_service,request_tele,...,callout_status,callout_outcome,discharge_wardid,acknowledge_status,createtime,updatetime,acknowledgetime,outcometime,firstreservationtime,currentreservationtime
0,3917,10017,199207,7,None,45,CCU,1,MED,1,...,Inactive,Discharged,45.0,Acknowledged,2149-05-31 10:44:34,2149-05-31 10:44:34,2149-05-31 15:08:04,2149-05-31 22:40:02,None,None
1,3919,10026,103770,33,None,3,SICU,3,NMED,1,...,Inactive,Discharged,3.0,Revised,2195-05-18 13:56:20,2195-05-19 15:45:30,None,2195-05-19 17:40:03,None,None
2,3920,10027,199395,12,None,55,CSRU,55,CSURG,1,...,Inactive,Discharged,55.0,Acknowledged,2190-07-20 08:15:20,2190-07-20 08:15:20,2190-07-20 08:57:46,2190-07-20 17:10:02,None,None
3,3921,10029,132349,33,None,45,SICU,1,MED,0,...,Inactive,Discharged,45.0,Acknowledged,2139-09-24 09:53:37,2139-09-24 09:53:37,2139-09-24 09:56:02,2139-09-25 19:10:01,None,None
4,3922,10033,157235,33,None,4,SICU,1,MED,1,...,Inactive,Discharged,4.0,Revised,2132-12-06 10:16:08,2132-12-06 14:53:53,None,2132-12-06 15:10:02,None,None

============================================================
 CAREGIVERS
============================================================

   row_id   cgid label            description
0    2228  16174    RO              Read Only
1    2229  16175    RO              Read Only
2    2230  16176   Res  Resident/Fellow/PA/NP
3    2231  16177    RO              Read Only
4    2232  16178    RT            Respiratory

============================================================
 CHARTEVENTS
============================================================

,row_id,subject_id,hadm_id,icustay_id,itemid,charttime,storetime,cgid,value,valuenum,valueuom,warning,error,resultstatus,stopped
0,5279021,40124,126179,279554.0,223761,2130-02-04 04:00:00,2130-02-04 04:35:00,19085,95.9,95.9,?F,0,0,None,None
1,5279022,40124,126179,279554.0,224695,2130-02-04 04:25:00,2130-02-04 05:55:00,18999,2222221.7,2222221.7,cmH2O,0,0,None,None
2,5279023,40124,126179,279554.0,220210,2130-02-04 04:30:00,2130-02-04 04:43:00,21452,15.0,15.0,insp/min,0,0,None,None
3,5279024,40124,126179,279554.0,220045,2130-02-04 04:32:00,2130-02-04 04:43:00,21452,94.0,94.0,bpm,0,0,None,None
4,5279025,40124,126179,279554.0,220179,2130-02-04 04:32:00,2130-02-04 04:43:00,21452,163.0,163.0,mmHg,0,0,None,None

============================================================
 CPTEVENTS
============================================================

,row_id,subject_id,hadm_id,costcenter,chartdate,cpt_cd,cpt_number,cpt_suffix,ticket_id_seq,sectionheader,subsectionheader,description
0,4615,10117,105150,ICU,None,99254,99254,None,1.0,Evaluation and management,Consultations,None
1,4616,10117,105150,ICU,None,99231,99231,None,2.0,Evaluation and management,Hospital inpatient services,None
2,4617,10117,105150,ICU,None,90935,90935,None,3.0,Medicine,Dialysis,None
3,4618,10117,105150,ICU,None,99231,99231,None,4.0,Evaluation and management,Hospital inpatient services,None
4,7753,10111,174739,ICU,None,99253,99253,None,1.0,Evaluation and management,Consultations,None

============================================================
 D_ICD_DIAGNOSES
============================================================

,row_id,icd9_code,short_title,long_title
0,1,01716,Erythem nod tb-oth test,"Erythema nodosum with hypersensitivity reaction in tuberculosis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]"
1,2,01720,TB periph lymph-unspec,"Tuberculosis of peripheral lymph nodes, unspecified"
2,3,01721,TB periph lymph-no exam,"Tuberculosis of peripheral lymph nodes, bacteriological or histological examination not done"
3,4,01722,TB periph lymph-exam unk,"Tuberculosis of peripheral lymph nodes, bacteriological or histological examination unknown (at present)"
4,5,01723,TB periph lymph-micro dx,"Tuberculosis of peripheral lymph nodes, tubercle bacilli found (in sputum) by microscopy"

============================================================
 D_ICD_PROCEDURES
============================================================

,row_id,icd9_code,short_title,long_title
0,1,1423,Chorioret les xenon coag,Destruction of chorioretinal lesion by xenon arc photocoagulation
1,2,1424,Chorioret les laser coag,Destruction of chorioretinal lesion by laser photocoagulation
2,3,1425,Chorioret les p/coag NOS,Destruction of chorioretinal lesion by photocoagulation of unspecified type
3,4,1426,Chorioret les radiother,Destruction of chorioretinal lesion by radiation therapy
4,5,1427,Chorioret les rad implan,Destruction of chorioretinal lesion by implantation of radiation source

============================================================
 D_ITEMS
============================================================

,row_id,itemid,label,abbreviation,dbsource,linksto,category,unitname,param_type,conceptid
0,1,1435,Sustained Nystamus,None,carevue,chartevents,None,None,None,None
1,2,1436,Tactile Disturbances,None,carevue,chartevents,None,None,None,None
2,3,1437,Tremor,None,carevue,chartevents,None,None,None,None
3,4,1438,Ulnar Pulse [Right],None,carevue,chartevents,None,None,None,None
4,5,1439,Visual Disturbances,None,carevue,chartevents,None,None,None,None

============================================================
 D_LABITEMS
============================================================

,row_id,itemid,label,fluid,category,loinc_code
0,1,50800,SPECIMEN TYPE,BLOOD,BLOOD GAS,None
1,2,50801,Alveolar-arterial Gradient,Blood,Blood Gas,19991-9
2,3,50802,Base Excess,Blood,Blood Gas,11555-0
3,4,50803,"Calculated Bicarbonate, Whole Blood",Blood,Blood Gas,1959-6
4,5,50804,Calculated Total CO2,Blood,Blood Gas,34728-6

============================================================
 DATETIMEEVENTS
============================================================

,row_id,subject_id,hadm_id,icustay_id,itemid,charttime,storetime,cgid,value,valueuom,warning,error,resultstatus,stopped
0,208474,10076,198503,201006.0,5684,2107-03-25 04:00:00,2107-03-25 04:34:00,20482,2107-03-24 00:00:00,Date,None,None,None,NotStopd
1,208475,10076,198503,201006.0,5684,2107-03-25 07:00:00,2107-03-25 07:06:00,15004,2107-03-24 00:00:00,Date,None,None,None,NotStopd
2,208836,10076,198503,201006.0,5684,2107-03-26 04:00:00,2107-03-26 05:31:00,20834,2107-03-24 00:00:00,Date,None,None,None,NotStopd
3,208837,10076,198503,201006.0,5684,2107-03-26 08:00:00,2107-03-26 08:33:00,17480,2107-03-24 00:00:00,Date,None,None,None,NotStopd
4,208838,10076,198503,201006.0,5684,2107-03-26 16:00:00,2107-03-26 16:08:00,17480,2107-03-24 00:00:00,Date,None,None,None,NotStopd

============================================================
 DIAGNOSES_ICD
============================================================

   row_id  subject_id  hadm_id  seq_num icd9_code
0  112344       10006   142345        1     99591
1  112345       10006   142345        2     99662
2  112346       10006   142345        3      5672
3  112347       10006   142345        4     40391
4  112348       10006   142345        5     42731

============================================================
 DRGCODES
============================================================

,row_id,subject_id,hadm_id,drg_type,drg_code,description,drg_severity,drg_mortality
0,1338,10130,156668,HCFA,148,"MAJOR SMALL & LARGE BOWEL PROCEDURES WITH COMPLICATIONS, COMORBIDITIES",None,None
1,2188,10114,167957,HCFA,518,"PERCUTANEOUS CARDIOVASCULAR PROCEDURES WITHOUT ACUTE MYOCARDIAL INFARCTION, WITHOUT CORONARY ARTERY STENT IMPLANT",None,None
2,2599,10117,187023,HCFA,185,DENTAL & ORAL DIS EXCEPT EXTRACTIONS & RESTORATIONS AGE >17,None,None
3,2703,10046,133110,HCFA,1,CRANIOTOMY AGE >17 EXCEPT FOR TRAUMA,None,None
4,3020,10011,105331,HCFA,205,"DISORDERS OF LIVER EXCEPT MALIGNANCY, CIRRHOSIS, ALCOHOLIC HEPATITIS WITH COMPLICATIONS, COMORBIDITIES",None,None

============================================================
 ICUSTAYS
============================================================

,row_id,subject_id,hadm_id,icustay_id,dbsource,first_careunit,last_careunit,first_wardid,last_wardid,intime,outtime,los
0,12742,10006,142345,206504,carevue,MICU,MICU,52,52,2164-10-23 21:10:15,2164-10-25 12:21:07,1.6325
1,12747,10011,105331,232110,carevue,MICU,MICU,15,15,2126-08-14 22:34:00,2126-08-28 18:59:00,13.8507
2,12749,10013,165520,264446,carevue,MICU,MICU,15,15,2125-10-04 23:38:00,2125-10-07 15:13:52,2.6499
3,12754,10017,199207,204881,carevue,CCU,CCU,7,7,2149-05-29 18:52:29,2149-05-31 22:19:17,2.1436
4,12755,10019,177759,228977,carevue,MICU,MICU,15,15,2163-05-14 20:43:56,2163-05-16 03:47:04,1.2938

============================================================
 INPUTEVENTS_CV
============================================================

,row_id,subject_id,hadm_id,icustay_id,charttime,itemid,amount,amountuom,rate,rateuom,...,orderid,linkorderid,stopped,newbottle,originalamount,originalamountuom,originalroute,originalrate,originalrateuom,originalsite
0,1184,10114,167957,234989,2171-11-03 15:00:00,30056,400.0,ml,None,None,...,2557279,2557279,None,None,None,ml,Oral,None,None,None
1,1185,10114,167957,234989,2171-11-03 20:00:00,30056,120.0,ml,None,None,...,7828849,2557279,None,None,None,ml,Oral,None,None,None
2,1186,10114,167957,234989,2171-11-03 23:00:00,30056,120.0,ml,None,None,...,2744159,2557279,None,None,None,ml,Oral,None,None,None
3,1187,10114,167957,234989,2171-11-04 02:00:00,30056,120.0,ml,None,None,...,8475006,2557279,None,None,None,ml,Oral,None,None,None
4,1188,10114,167957,234989,2171-11-04 05:00:00,30056,120.0,ml,None,None,...,11183474,2557279,None,None,None,ml,Oral,None,None,None

============================================================
 INPUTEVENTS_MV
============================================================

,row_id,subject_id,hadm_id,icustay_id,starttime,endtime,itemid,amount,amountuom,rate,...,totalamountuom,isopenbag,continueinnextdept,cancelreason,statusdescription,comments_editedby,comments_canceledby,comments_date,originalamount,originalrate
0,118897,42367,139932,250305,2147-10-29 16:45:00,2147-10-29 16:46:00,225799,60.000000,ml,NaN,...,ml,0,0,0,FinishedRunning,None,None,None,60.0,60.000000
1,118898,42367,139932,250305,2147-10-20 13:17:00,2147-10-20 13:18:00,223258,10.000000,units,NaN,...,None,0,0,1,Rewritten,None,RN,2147-10-20 13:18:00,10.0,10.000000
2,118899,42367,139932,250305,2147-10-29 03:23:00,2147-10-29 03:53:00,226089,99.999999,ml,199.999998,...,ml,0,0,0,FinishedRunning,None,None,None,100.0,200.000000
3,118900,42367,139932,250305,2147-10-22 22:00:00,2147-10-22 22:01:00,225799,40.000000,ml,NaN,...,ml,0,0,0,FinishedRunning,None,None,None,40.0,40.000000
4,118901,42367,139932,250305,2147-10-16 06:21:00,2147-10-17 06:10:00,225936,1309.899995,ml,54.999300,...,ml,0,0,0,FinishedRunning,None,None,None,1309.9,54.999298

============================================================
 LABEVENTS
============================================================

,row_id,subject_id,hadm_id,itemid,charttime,value,valuenum,valueuom,flag
0,6244563,10006,None,50868,2164-09-24 20:21:00,19,19.0,mEq/L,None
1,6244564,10006,None,50882,2164-09-24 20:21:00,27,27.0,mEq/L,None
2,6244565,10006,None,50893,2164-09-24 20:21:00,10.0,10.0,mg/dL,None
3,6244566,10006,None,50902,2164-09-24 20:21:00,97,97.0,mEq/L,None
4,6244567,10006,None,50912,2164-09-24 20:21:00,7.0,7.0,mg/dL,abnormal

============================================================
 MICROBIOLOGYEVENTS
============================================================

,row_id,subject_id,hadm_id,chartdate,charttime,spec_itemid,spec_type_desc,org_itemid,org_name,isolate_num,ab_itemid,ab_name,dilution_text,dilution_comparison,dilution_value,interpretation
0,134694,10006,142345,2164-10-23,2164-10-23 15:30:00,70012,BLOOD CULTURE,80155.0,"STAPHYLOCOCCUS, COAGULASE NEGATIVE",2.0,NaN,None,None,None,NaN,None
1,134695,10006,142345,2164-10-23,2164-10-23 15:30:00,70012,BLOOD CULTURE,80155.0,"STAPHYLOCOCCUS, COAGULASE NEGATIVE",1.0,90015.0,VANCOMYCIN,2,=,2.0,S
2,134696,10006,142345,2164-10-23,2164-10-23 15:30:00,70012,BLOOD CULTURE,80155.0,"STAPHYLOCOCCUS, COAGULASE NEGATIVE",1.0,90012.0,GENTAMICIN,<=0.5,<=,1.0,S
3,134697,10006,142345,2164-10-23,2164-10-23 15:30:00,70012,BLOOD CULTURE,80155.0,"STAPHYLOCOCCUS, COAGULASE NEGATIVE",1.0,90025.0,LEVOFLOXACIN,4,=,4.0,I
4,134698,10006,142345,2164-10-23,2164-10-23 15:30:00,70012,BLOOD CULTURE,80155.0,"STAPHYLOCOCCUS, COAGULASE NEGATIVE",1.0,90016.0,OXACILLIN,=>4,=>,4.0,R

============================================================
 OUTPUTEVENTS
============================================================

,row_id,subject_id,hadm_id,icustay_id,charttime,itemid,value,valueuom,storetime,cgid,stopped,newbottle,iserror
0,6540,10114,167957,234989.0,2171-10-30 20:00:00,40055,39.0,ml,2171-10-30 20:38:00,15029,None,None,None
1,6541,10114,167957,234989.0,2171-10-30 21:00:00,40055,35.0,ml,2171-10-30 21:18:00,15029,None,None,None
2,6542,10114,167957,234989.0,2171-10-30 23:00:00,40055,100.0,ml,2171-10-30 23:31:00,15029,None,None,None
3,6543,10114,167957,234989.0,2171-10-31 00:00:00,40055,45.0,ml,2171-10-31 00:24:00,15029,None,None,None
4,6544,10114,167957,234989.0,2171-10-31 02:00:00,40055,80.0,ml,2171-10-31 02:02:00,15029,None,None,None

============================================================
 PATIENTS
============================================================

,row_id,subject_id,gender,dob,dod,dod_hosp,dod_ssn,expire_flag
0,9467,10006,F,2094-03-05,2165-08-12,2165-08-12,2165-08-12,1
1,9472,10011,F,2090-06-05,2126-08-28,2126-08-28,None,1
2,9474,10013,F,2038-09-03,2125-10-07,2125-10-07,2125-10-07,1
3,9478,10017,F,2075-09-21,2152-09-12,None,2152-09-12,1
4,9479,10019,M,2114-06-20,2163-05-15,2163-05-15,2163-05-15,1

============================================================
 PRESCRIPTIONS
============================================================

,row_id,subject_id,hadm_id,icustay_id,startdate,enddate,drug_type,drug,drug_name_poe,drug_name_generic,formulary_drug_cd,gsn,ndc,prod_strength,dose_val_rx,dose_unit_rx,form_val_disp,form_unit_disp,route
0,32600,42458,159647,None,2146-07-21,2146-07-22,MAIN,Pneumococcal Vac Polyvalent,Pneumococcal Vac Polyvalent,PNEUMOcoccal Vac Polyvalent,PNEU25I,48548.0,6494300.0,25mcg/0.5mL Vial,0.5,mL,1,VIAL,IM
1,32601,42458,159647,None,2146-07-21,2146-07-22,MAIN,Bisacodyl,Bisacodyl,Bisacodyl,BISA5,2947.0,536338101.0,5 mg Tab,10,mg,2,TAB,PO
2,32602,42458,159647,None,2146-07-21,2146-07-22,MAIN,Bisacodyl,Bisacodyl,Bisacodyl (Rectal),BISA10R,2944.0,574705050.0,10mg Suppository,10,mg,1,SUPP,PR
3,32603,42458,159647,None,2146-07-21,2146-07-22,MAIN,Senna,Senna,Senna,SENN187,19964.0,904516561.0,1 Tablet,1,TAB,1,TAB,PO
4,32604,42458,159647,None,2146-07-21,2146-07-21,MAIN,Docusate Sodium (Liquid),Docusate Sodium (Liquid),Docusate Sodium (Liquid),DOCU100L,3017.0,121054410.0,100mg UD Cup,100,mg,1,UDCUP,PO

============================================================
 PROCEDURES_ICD
============================================================

   row_id  subject_id  hadm_id  seq_num  icd9_code
0    3994       10114   167957        1       3605
1    3995       10114   167957        2       3722
2    3996       10114   167957        3       8856
3    3997       10114   167957        4       9920
4    3998       10114   167957        5       9671

============================================================
 SERVICES
============================================================

   row_id  subject_id  hadm_id         transfertime prev_service curr_service
0   14974       10006   142345  2164-10-23 21:10:15         None          MED
1   14979       10011   105331  2126-08-14 22:34:00         None          MED
2   14981       10013   165520  2125-10-04 23:38:00         None          MED
3   14985       10017   199207  2149-05-26 17:21:09         None          MED
4   14986       10019   177759  2163-05-14 20:43:56         None          MED

============================================================
 TRANSFERS
============================================================

,row_id,subject_id,hadm_id,icustay_id,dbsource,eventtype,prev_careunit,curr_careunit,prev_wardid,curr_wardid,intime,outtime,los
0,54440,10006,142345,206504.0,carevue,admit,None,MICU,NaN,52.0,2164-10-23 21:10:15,2164-10-25 12:21:07,39.18
1,54441,10006,142345,NaN,carevue,transfer,MICU,None,52.0,45.0,2164-10-25 12:21:07,2164-11-01 17:14:27,172.89
2,54442,10006,142345,NaN,carevue,discharge,None,None,45.0,NaN,2164-11-01 17:14:27,None,NaN
3,54460,10011,105331,232110.0,carevue,admit,None,MICU,NaN,15.0,2126-08-14 22:34:00,2126-08-28 18:59:00,332.42
4,54461,10011,105331,NaN,carevue,discharge,MICU,None,15.0,NaN,2126-08-28 18:59:00,None,NaN

In [12]:
# Column info for every table
tables = conn.execute(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
).fetchall()

for (t,) in tables:
    print(f"\n{'='*60}")
    print(f"  {t.upper()}")
    print(f"{'='*60}")
    display(pd.read_sql(f"PRAGMA table_info({t})", conn))

============================================================
  ADMISSIONS
============================================================

    cid                  name     type  notnull dflt_value  pk
0     0                row_id  INTEGER        0       None   0
1     1            subject_id  INTEGER        0       None   0
2     2               hadm_id  INTEGER        0       None   0
3     3             admittime     TEXT        0       None   0
4     4             dischtime     TEXT        0       None   0
5     5             deathtime     TEXT        0       None   0
6     6        admission_type     TEXT        0       None   0
7     7    admission_location     TEXT        0       None   0
8     8    discharge_location     TEXT        0       None   0
9     9             insurance     TEXT        0       None   0
10   10              language     TEXT        0       None   0
11   11              religion     TEXT        0       None   0
12   12        marital_status     TEXT        0       None   0
13   13             ethnicity     TEXT        0       None   0
14   14             edregtime     TEXT        0       None   0
15   15             edouttime     TEXT        0       None   0
16   16             diagnosis     TEXT        0       None   0
17   17  hospital_expire_flag  INTEGER        0       None   0
18   18  has_chartevents_data  INTEGER        0       None   0

============================================================
  CALLOUT
============================================================

    cid                    name     type  notnull dflt_value  pk
0     0                  row_id  INTEGER        0       None   0
1     1              subject_id  INTEGER        0       None   0
2     2                 hadm_id  INTEGER        0       None   0
3     3           submit_wardid  INTEGER        0       None   0
4     4         submit_careunit     TEXT        0       None   0
5     5             curr_wardid  INTEGER        0       None   0
6     6           curr_careunit     TEXT        0       None   0
7     7          callout_wardid  INTEGER        0       None   0
8     8         callout_service     TEXT        0       None   0
9     9            request_tele  INTEGER        0       None   0
10   10            request_resp  INTEGER        0       None   0
11   11           request_cdiff  INTEGER        0       None   0
12   12            request_mrsa  INTEGER        0       None   0
13   13             request_vre  INTEGER        0       None   0
14   14          callout_status     TEXT        0       None   0
15   15         callout_outcome     TEXT        0       None   0
16   16        discharge_wardid     REAL        0       None   0
17   17      acknowledge_status     TEXT        0       None   0
18   18              createtime     TEXT        0       None   0
19   19              updatetime     TEXT        0       None   0
20   20         acknowledgetime     TEXT        0       None   0
21   21             outcometime     TEXT        0       None   0
22   22    firstreservationtime     TEXT        0       None   0
23   23  currentreservationtime     TEXT        0       None   0

============================================================
  CAREGIVERS
============================================================

   cid         name     type  notnull dflt_value  pk
0    0       row_id  INTEGER        0       None   0
1    1         cgid  INTEGER        0       None   0
2    2        label     TEXT        0       None   0
3    3  description     TEXT        0       None   0

============================================================
  CHARTEVENTS
============================================================

    cid          name     type  notnull dflt_value  pk
0     0        row_id  INTEGER        0       None   0
1     1    subject_id  INTEGER        0       None   0
2     2       hadm_id  INTEGER        0       None   0
3     3    icustay_id     REAL        0       None   0
4     4        itemid  INTEGER        0       None   0
5     5     charttime     TEXT        0       None   0
6     6     storetime     TEXT        0       None   0
7     7          cgid  INTEGER        0       None   0
8     8         value     REAL        0       None   0
9     9      valuenum     REAL        0       None   0
10   10      valueuom     TEXT        0       None   0
11   11       warning  INTEGER        0       None   0
12   12         error  INTEGER        0       None   0
13   13  resultstatus     REAL        0       None   0
14   14       stopped     REAL        0       None   0

============================================================
  CPTEVENTS
============================================================

    cid              name     type  notnull dflt_value  pk
0     0            row_id  INTEGER        0       None   0
1     1        subject_id  INTEGER        0       None   0
2     2           hadm_id  INTEGER        0       None   0
3     3        costcenter     TEXT        0       None   0
4     4         chartdate     TEXT        0       None   0
5     5            cpt_cd  INTEGER        0       None   0
6     6        cpt_number  INTEGER        0       None   0
7     7        cpt_suffix     REAL        0       None   0
8     8     ticket_id_seq     REAL        0       None   0
9     9     sectionheader     TEXT        0       None   0
10   10  subsectionheader     TEXT        0       None   0
11   11       description     TEXT        0       None   0

============================================================
  D_ICD_DIAGNOSES
============================================================

   cid         name     type  notnull dflt_value  pk
0    0       row_id  INTEGER        0       None   0
1    1    icd9_code     TEXT        0       None   0
2    2  short_title     TEXT        0       None   0
3    3   long_title     TEXT        0       None   0

============================================================
  D_ICD_PROCEDURES
============================================================

   cid         name     type  notnull dflt_value  pk
0    0       row_id  INTEGER        0       None   0
1    1    icd9_code  INTEGER        0       None   0
2    2  short_title     TEXT        0       None   0
3    3   long_title     TEXT        0       None   0

============================================================
  D_ITEMS
============================================================

   cid          name     type  notnull dflt_value  pk
0    0        row_id  INTEGER        0       None   0
1    1        itemid  INTEGER        0       None   0
2    2         label     TEXT        0       None   0
3    3  abbreviation     TEXT        0       None   0
4    4      dbsource     TEXT        0       None   0
5    5       linksto     TEXT        0       None   0
6    6      category     TEXT        0       None   0
7    7      unitname     TEXT        0       None   0
8    8    param_type     TEXT        0       None   0
9    9     conceptid     REAL        0       None   0

============================================================
  D_LABITEMS
============================================================

   cid        name     type  notnull dflt_value  pk
0    0      row_id  INTEGER        0       None   0
1    1      itemid  INTEGER        0       None   0
2    2       label     TEXT        0       None   0
3    3       fluid     TEXT        0       None   0
4    4    category     TEXT        0       None   0
5    5  loinc_code     TEXT        0       None   0

============================================================
  DATETIMEEVENTS
============================================================

    cid          name     type  notnull dflt_value  pk
0     0        row_id  INTEGER        0       None   0
1     1    subject_id  INTEGER        0       None   0
2     2       hadm_id  INTEGER        0       None   0
3     3    icustay_id     REAL        0       None   0
4     4        itemid  INTEGER        0       None   0
5     5     charttime     TEXT        0       None   0
6     6     storetime     TEXT        0       None   0
7     7          cgid  INTEGER        0       None   0
8     8         value     TEXT        0       None   0
9     9      valueuom     TEXT        0       None   0
10   10       warning     REAL        0       None   0
11   11         error     REAL        0       None   0
12   12  resultstatus     REAL        0       None   0
13   13       stopped     TEXT        0       None   0

============================================================
  DIAGNOSES_ICD
============================================================

   cid        name     type  notnull dflt_value  pk
0    0      row_id  INTEGER        0       None   0
1    1  subject_id  INTEGER        0       None   0
2    2     hadm_id  INTEGER        0       None   0
3    3     seq_num  INTEGER        0       None   0
4    4   icd9_code     TEXT        0       None   0

============================================================
  DRGCODES
============================================================

   cid           name     type  notnull dflt_value  pk
0    0         row_id  INTEGER        0       None   0
1    1     subject_id  INTEGER        0       None   0
2    2        hadm_id  INTEGER        0       None   0
3    3       drg_type     TEXT        0       None   0
4    4       drg_code  INTEGER        0       None   0
5    5    description     TEXT        0       None   0
6    6   drg_severity     REAL        0       None   0
7    7  drg_mortality     REAL        0       None   0

============================================================
  ICUSTAYS
============================================================

    cid            name     type  notnull dflt_value  pk
0     0          row_id  INTEGER        0       None   0
1     1      subject_id  INTEGER        0       None   0
2     2         hadm_id  INTEGER        0       None   0
3     3      icustay_id  INTEGER        0       None   0
4     4        dbsource     TEXT        0       None   0
5     5  first_careunit     TEXT        0       None   0
6     6   last_careunit     TEXT        0       None   0
7     7    first_wardid  INTEGER        0       None   0
8     8     last_wardid  INTEGER        0       None   0
9     9          intime     TEXT        0       None   0
10   10         outtime     TEXT        0       None   0
11   11             los     REAL        0       None   0

============================================================
  INPUTEVENTS_CV
============================================================

    cid               name     type  notnull dflt_value  pk
0     0             row_id  INTEGER        0       None   0
1     1         subject_id  INTEGER        0       None   0
2     2            hadm_id  INTEGER        0       None   0
3     3         icustay_id  INTEGER        0       None   0
4     4          charttime     TEXT        0       None   0
5     5             itemid  INTEGER        0       None   0
6     6             amount     REAL        0       None   0
7     7          amountuom     TEXT        0       None   0
8     8               rate     REAL        0       None   0
9     9            rateuom     TEXT        0       None   0
10   10          storetime     TEXT        0       None   0
11   11               cgid     REAL        0       None   0
12   12            orderid  INTEGER        0       None   0
13   13        linkorderid  INTEGER        0       None   0
14   14            stopped     TEXT        0       None   0
15   15          newbottle     REAL        0       None   0
16   16     originalamount     REAL        0       None   0
17   17  originalamountuom     TEXT        0       None   0
18   18      originalroute     TEXT        0       None   0
19   19       originalrate     REAL        0       None   0
20   20    originalrateuom     TEXT        0       None   0
21   21       originalsite     TEXT        0       None   0

============================================================
  INPUTEVENTS_MV
============================================================

    cid                           name     type  notnull dflt_value  pk
0     0                         row_id  INTEGER        0       None   0
1     1                     subject_id  INTEGER        0       None   0
2     2                        hadm_id  INTEGER        0       None   0
3     3                     icustay_id  INTEGER        0       None   0
4     4                      starttime     TEXT        0       None   0
5     5                        endtime     TEXT        0       None   0
6     6                         itemid  INTEGER        0       None   0
7     7                         amount     REAL        0       None   0
8     8                      amountuom     TEXT        0       None   0
9     9                           rate     REAL        0       None   0
10   10                        rateuom     TEXT        0       None   0
11   11                      storetime     TEXT        0       None   0
12   12                           cgid  INTEGER        0       None   0
13   13                        orderid  INTEGER        0       None   0
14   14                    linkorderid  INTEGER        0       None   0
15   15              ordercategoryname     TEXT        0       None   0
16   16     secondaryordercategoryname     TEXT        0       None   0
17   17  ordercomponenttypedescription     TEXT        0       None   0
18   18       ordercategorydescription     TEXT        0       None   0
19   19                  patientweight     REAL        0       None   0
20   20                    totalamount     REAL        0       None   0
21   21                 totalamountuom     TEXT        0       None   0
22   22                      isopenbag  INTEGER        0       None   0
23   23             continueinnextdept  INTEGER        0       None   0
24   24                   cancelreason  INTEGER        0       None   0
25   25              statusdescription     TEXT        0       None   0
26   26              comments_editedby     TEXT        0       None   0
27   27            comments_canceledby     TEXT        0       None   0
28   28                  comments_date     TEXT        0       None   0
29   29                 originalamount     REAL        0       None   0
30   30                   originalrate     REAL        0       None   0

============================================================
  LABEVENTS
============================================================

   cid        name     type  notnull dflt_value  pk
0    0      row_id  INTEGER        0       None   0
1    1  subject_id  INTEGER        0       None   0
2    2     hadm_id     REAL        0       None   0
3    3      itemid  INTEGER        0       None   0
4    4   charttime     TEXT        0       None   0
5    5       value     TEXT        0       None   0
6    6    valuenum     REAL        0       None   0
7    7    valueuom     TEXT        0       None   0
8    8        flag     TEXT        0       None   0

============================================================
  MICROBIOLOGYEVENTS
============================================================

    cid                 name     type  notnull dflt_value  pk
0     0               row_id  INTEGER        0       None   0
1     1           subject_id  INTEGER        0       None   0
2     2              hadm_id  INTEGER        0       None   0
3     3            chartdate     TEXT        0       None   0
4     4            charttime     TEXT        0       None   0
5     5          spec_itemid  INTEGER        0       None   0
6     6       spec_type_desc     TEXT        0       None   0
7     7           org_itemid     REAL        0       None   0
8     8             org_name     TEXT        0       None   0
9     9          isolate_num     REAL        0       None   0
10   10            ab_itemid     REAL        0       None   0
11   11              ab_name     TEXT        0       None   0
12   12        dilution_text     TEXT        0       None   0
13   13  dilution_comparison     TEXT        0       None   0
14   14       dilution_value     REAL        0       None   0
15   15       interpretation     TEXT        0       None   0

============================================================
  OUTPUTEVENTS
============================================================

    cid        name     type  notnull dflt_value  pk
0     0      row_id  INTEGER        0       None   0
1     1  subject_id  INTEGER        0       None   0
2     2     hadm_id  INTEGER        0       None   0
3     3  icustay_id     REAL        0       None   0
4     4   charttime     TEXT        0       None   0
5     5      itemid  INTEGER        0       None   0
6     6       value     REAL        0       None   0
7     7    valueuom     TEXT        0       None   0
8     8   storetime     TEXT        0       None   0
9     9        cgid  INTEGER        0       None   0
10   10     stopped     REAL        0       None   0
11   11   newbottle     REAL        0       None   0
12   12     iserror     REAL        0       None   0

============================================================
  PATIENTS
============================================================

   cid         name     type  notnull dflt_value  pk
0    0       row_id  INTEGER        0       None   0
1    1   subject_id  INTEGER        0       None   0
2    2       gender     TEXT        0       None   0
3    3          dob     TEXT        0       None   0
4    4          dod     TEXT        0       None   0
5    5     dod_hosp     TEXT        0       None   0
6    6      dod_ssn     TEXT        0       None   0
7    7  expire_flag  INTEGER        0       None   0

============================================================
  PRESCRIPTIONS
============================================================

    cid               name     type  notnull dflt_value  pk
0     0             row_id  INTEGER        0       None   0
1     1         subject_id  INTEGER        0       None   0
2     2            hadm_id  INTEGER        0       None   0
3     3         icustay_id     REAL        0       None   0
4     4          startdate     TEXT        0       None   0
5     5            enddate     TEXT        0       None   0
6     6          drug_type     TEXT        0       None   0
7     7               drug     TEXT        0       None   0
8     8      drug_name_poe     TEXT        0       None   0
9     9  drug_name_generic     TEXT        0       None   0
10   10  formulary_drug_cd     TEXT        0       None   0
11   11                gsn     REAL        0       None   0
12   12                ndc     REAL        0       None   0
13   13      prod_strength     TEXT        0       None   0
14   14        dose_val_rx     TEXT        0       None   0
15   15       dose_unit_rx     TEXT        0       None   0
16   16      form_val_disp     TEXT        0       None   0
17   17     form_unit_disp     TEXT        0       None   0
18   18              route     TEXT        0       None   0

============================================================
  PROCEDURES_ICD
============================================================

   cid        name     type  notnull dflt_value  pk
0    0      row_id  INTEGER        0       None   0
1    1  subject_id  INTEGER        0       None   0
2    2     hadm_id  INTEGER        0       None   0
3    3     seq_num  INTEGER        0       None   0
4    4   icd9_code  INTEGER        0       None   0

============================================================
  SERVICES
============================================================

   cid          name     type  notnull dflt_value  pk
0    0        row_id  INTEGER        0       None   0
1    1    subject_id  INTEGER        0       None   0
2    2       hadm_id  INTEGER        0       None   0
3    3  transfertime     TEXT        0       None   0
4    4  prev_service     TEXT        0       None   0
5    5  curr_service     TEXT        0       None   0

============================================================
  TRANSFERS
============================================================

    cid           name     type  notnull dflt_value  pk
0     0         row_id  INTEGER        0       None   0
1     1     subject_id  INTEGER        0       None   0
2     2        hadm_id  INTEGER        0       None   0
3     3     icustay_id     REAL        0       None   0
4     4       dbsource     TEXT        0       None   0
5     5      eventtype     TEXT        0       None   0
6     6  prev_careunit     TEXT        0       None   0
7     7  curr_careunit     TEXT        0       None   0
8     8    prev_wardid     REAL        0       None   0
9     9    curr_wardid     REAL        0       None   0
10   10         intime     TEXT        0       None   0
11   11        outtime     TEXT        0       None   0
12   12            los     REAL        0       None   0

In [ ]:

# # Register views from features.sql file
# sql = open('../sql/features.sql').read()

# for stmt in [s.strip() for s in sql.split(';') if s.strip()]:
#     try:
#         conn.execute(stmt)
#     except
#         pass

# # Query any view
# df = pd.read_sql(
#     'SELECT * FROM v_cohort LIMIT 10',
#     conn
# )